spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/testing?characterEncoding=utf8
        username: tommy
        password: 7Kcr4iv3
        connection-test-query: "SELECT 1"
        test-while-idle: true
        test-on-borrow: false
        
mybatis:
    mapperLocations: classpath*:**/sqlmappers/*.xml
    
custom:
    admins:
        - tommy.yeh1112@gmail.com
        - alicechen1013@gmail.com